name: jaguar_http_gen
description: Generator for jaguar_http, a Retrofit inspired declarative HTTP client.
version: 2.2.0
authors:
- Hadrien Lejard <hadrien.lejard@gmail.com>
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/client

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  analyzer: ^0.32.0
  build: ^0.12.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5
  jaguar_http: ^2.2.0

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.10.0
  collection: ^1.14.10
  path: ^1.6.2

dependency_overrides:
  jaguar_http:
    path: ../jaguar_http
