name: client_cookie
description: Emulates Cookie store for dart:io and Flutter as if its a Browser. Parses cookies from 'set-cookie' response header and also writes cookies to request header.
version: 3.0.2
homepage: https://github.com/Jaguar-dart/client_cookie

documentation:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:
  test: ^1.16.0
