name: declarative_client
description: Retrofit inspired declarative Http client for Dart.
version: 2.1.1
authors:
- Hadrien Lejard <hadrien.lejard@gmail.com>
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/client

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

dependencies:
  jaguar_serializer: ^2.1.9
  http: ^0.11.3
  meta: ^1.1.5
  jaguar_client: ^2.1.4

dev_dependencies:
  test: 1.2.0
  jaguar_serializer_cli:
  build_runner:

dependency_overrides:
  jaguar_client:
    path: ../jaguar_client
