name: jaguar_client
description: Write concise JSON API clients
version: 2.1.4
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/client
documentation:

environment:
  sdk: ">=2.0.0-dev.65.0 <3.0.0"

dependencies:
  http: ^0.11.3
  jaguar_serializer: ^2.1.9
  jaguar_common: ^0.2.1
  auth_header: ^0.0.3
  client_cookie: ^2.1.2
  jaguar_resty: ^2.5.10
  async: ^2.0.7

dev_dependencies:
  jaguar: ^2.1.8
  test: ^1.2.0
  jaguar_reflect: ^2.1.2
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
  jaguar_serializer_cli: ^2.1.19
