name: jaguar_client
description: Write concise JSON API clients. Uses jaguar_serializer for automatic serialization. Supports cookies, interceptors and authentication.
version: 2.2.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/client
documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ^0.11.3
  jaguar_serializer: ^2.2.0
  auth_header: ^2.1.1
  client_cookie: ^2.1.2
  jaguar_resty: ^2.6.1
  async: ^2.0.7

dev_dependencies:
  jaguar: ^2.1.37
  test: ^1.3.0
  jaguar_reflect: ^2.1.4
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  jaguar_serializer_cli: ^2.2.0
