name: jaguar_http
description: Retrofit inspired declarative HTTP client for Dart.
version: 2.2.0
authors:
- Hadrien Lejard <hadrien.lejard@gmail.com>
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/client

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar_serializer: ^2.2.0
  http: ^0.11.3
  meta: ^1.1.5
  # jaguar_client: ^2.2.2
  jaguar_resty: ^2.6.0

dev_dependencies:
  test: ^1.3.0
  jaguar_serializer_cli: ^2.2.0
  build_runner:
  jaguar: ^2.2.20
  jaguar_http_gen:
    path: ../jaguar_http_gen
