name: jaguar_resty
description: Build fluent functional REST clients. Supports interceptors, cookies, multipart forms and authenticators.
version: 3.0.0
homepage: https://github.com/Jaguar-dart/client

documentation:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  async: ^2.5.0
  http_parser: ^4.0.0
  client_cookie: ^3.0.0
  collection: ^1.14.6
  auth_header: ^3.0.0
  path: ^1.8.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.16.0
  # jaguar: ^2.4.1
