name: jaguar_resty
description: Build fluent functional Restful clients
version: 2.5.6
homepage: https://github.com/Jaguar-dart/resty
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.3
  async: ^2.0.6
  http_parser: ^3.1.1
  client_cookie: ^2.1.2
  collection: ^1.14.6
  auth_header: ^0.0.3

dev_dependencies:
  test: ^0.12.0
  jaguar: ^2.0.1
